# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MireaApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MireaApp
  pod 'ActiveLabel'
  pod 'TinyConstraints'
  target 'MireaAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MireaAppUITests' do
    # Pods for testing
  end

end
